# Generated by Django 5.2.3 on 2025-06-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Message_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='size',
            field=models.IntegerField(default=1),
        ),
    ]
